[package]
edition = "2024"
name = "board-rp"
version = "0.1.0"
license = "MIT or Apache-2.0"

[build-dependencies]
regex = { version = "1.11.0" }

[dependencies]
defmt = { version = "1" }
defmt-rtt = { version = "1" }
fixed = { version = "1.29.0" }
heapless = { version = "0.9.3" }
portable-atomic = { version = "1.5", features = ["critical-section"] } # required for static_cell
rand_core = { version = "0.9" }
static_cell = { version = "2" }

embassy-embedded-hal = { version = "0.6.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-futures = { version = "0.1.2" }
embassy-sync = { version = "0.8.0" }
embassy-time = { version = "0.5.1" }

embedded-hal-1 = { version = "1.0", package = "embedded-hal" }
embedded-hal-async = { version = "1.0.0", features = ["defmt-03"] }
embedded-io-async = { version = "0.7" }

cortex-m-rt = { version = "0.7" }

embedded-graphics-examples = { path = ".." }
mipidsi = "0.10.0"
embedded-graphics = "0.8.2"
micromath = "2.1.0"
embedded-graphics-framebuf = "0.5.0"

[target.'cfg( target_arch = "arm" )'.dependencies]
panic-probe = { version = "1", features = ["print-defmt"] }

[target.'cfg( target_arch = "riscv32" )'.dependencies]
panic-halt = { version = "1.0.0" }

[target."thumbv6m-none-eabi".dependencies]
embassy-rp = { version = "0.10.0", features = [
    "time-driver", "critical-section-impl", "binary-info", "defmt", "unstable-pac",
    "rp2040",
] }

[target."thumbv8m.main-none-eabihf".dependencies]
embassy-rp = { version = "0.10.0", features = [
    "time-driver", "critical-section-impl", "binary-info", "defmt", "unstable-pac",
    "rp235xa",
] }

[target."riscv32imac-unknown-none-elf".dependencies]
embassy-rp = { version = "0.10.0", features = [
    "time-driver", "critical-section-impl", "binary-info", "defmt", "unstable-pac",
    "rp235xa",
] }
