[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]
target = "xtensa-esp32-none-elf"

[env]

[unstable]
build-std = ["core", "alloc"]
